name: requests_module
description: Module for request.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  readmore: ^2.2.0
  freezed: ^2.0.3+1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  freezed_annotation: ^2.1.0
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  auto_route: ^5.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_form_builder: ^7.7.0
  flutter_bloc: ^8.1.1
  universal_html: ^2.0.8
  filter_list: ^1.0.2
  http: ^0.13.5
  jiffy: ^5.0.0
  retrofit: ^3.3.1
  responsive_framework: ^0.2.0
  dotted_border: ^2.0.0+2
  flutter_keyboard_visibility: ^5.4.0
  scrollable_positioned_list: ^0.3.5
  intl: ^0.17.0
  enum_to_string: ^2.0.1
  fluttertoast: ^8.0.9
  provider: ^6.0.4
  easy_localization: ^3.0.1
  file_picker: ^5.2.5
  camera: ^0.10.1
  form_builder_validators: ^8.4.0
  devicelocale: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=4.2.0 <5.0.0'
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  auto_route_generator: ^5.0.2


  common_module:
    path: ../common_module

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-Italic.ttf
          style: italic